### ISSUE TITLE
WaitForm tidy up

### ISSUE THREAD

**Issue by alistair-ward** [openTemplot/templot3#99]
In unit wait_message.pas

Rather than have a single auto-created form that is updated, I suggest creating on the fly as required using a constructor with all required parameters.

Consider using an interfaced object (Delphi-style interface), so that it is automatically  cleaned up when going out of scope.

**Comment by graeme-defty** [comment]
Sorry, I am not seeing the issue here.

Is the benefit in the automatic clean-up?

**Comment by alistair-ward** [comment]
My apologies for lack of clarity here. The problem (as I see it) is more in the *usage* of the wait form.

There are multiple places where the wait form is used. In each place there are multiple lines of code setting properties etc, with duplicated logic around setting control sizes etc, 

Cleaning up the usage could be done by:
1) a public procedure that takes the desired parameters and displays the single instance of the form, with a matching hide procedure.
2) a public procedure/constructor that creates an instance of the wait form on demand and sets properties appropriately, which can then be free'd
3) (possibly a step too far...) a public procedure/constructor that creates an instance of the wait form, and then returns a Delphi-style interface (reference counted object), that will then *automatically* be deleted when the variable goes out of scope

Reasons for making this change:
* eliminating duplicated logic, and simplifying all the call sites where a wait form is used.
* (possibly) eliminate an auto-created form. A lot of Delphi apps create a single instance of each form used in an application at startup. This is a big reason why the app can be slow to start.
* using the interface approach further simplifies the call site code, as there will be no need to manually hide/free the form.

**Comment by graeme-defty** [comment]
The first of your reasons is more than good enough for me.  :-)

As to which of the implementations, I would always gravitate to the simplest, in the absence of any other obvious factors. Your choice.
